creacion de contenedor de filtros
abfleitas/DriveIn pull request #7
Opened 2022-11-08 14:38 UTC by arielbg00

2022-11-08 14:46 UTC, abfleitas requested changes
Son filtros, no ordenamiento, Los filtros tienen que ser de tipo check-box, la categoria( chico, mediano, grande, premiun, convertible), la transmision( manual y automatico), y las caracteristicas serian, aire acondicionado y +4 asientos

2022-11-08 15:19 UTC, Javymoyano requested changes

2022-11-08 15:19 UTC, Javymoyano commented on client/src/components/Filters/Filters.jsx
> +            <option value="caracteristicas">Características</option>
Creo que no hay una propiedad "caracteristicas", pero me parece que puede ir ordenado por "Asientos"

2022-11-08 15:41 UTC, arielbg00 commented on client/src/components/Filters/Filters.jsx
> +            <option value="caracteristicas">Características</option>
ahi lo modifique usando checkbox

2022-11-08 15:47 UTC, jagustinrm requested changes

2022-11-08 15:47 UTC, jagustinrm commented on client/src/components/Filters/Filters.jsx
> +            <input type="checkbox" name="chico" />chico
Pondría las propiedades en inglés.

2022-11-08 16:01 UTC, arielbg00 commented on client/src/components/Filters/Filters.jsx
> +            <input type="checkbox" name="chico" />chico
decis name="short" ? o todo? a category

2022-11-08 16:31 UTC, luqasmagra approved these changes

2022-11-09 00:17 UTC, jagustinrm commented on client/src/components/Filters/Filters.jsx
> +            <input type="checkbox" name="chico" />chico
claro, a todos los "name"

2022-11-09 14:15 UTC, verojuy approved these changes

2022-11-09 14:15 UTC, jagustinrm approved these changes

2022-11-09 14:16 UTC, merged